github.com:
    users:
        TiltedToast:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: TiltedToast
