{ pkgs, config, ... }:

{
  environment.systemPackages =
    with pkgs;
    [
      cachix
      file
      gcc
      moar
      dust
      rm-improved
      wget
      gnumake
      ninja
      git
      delta
      unzip
      zsh
      stow
      curl
      cmake
      imagemagick
      gifsicle
      openssh
      openssl
      oh-my-posh
      fzf
      atuin
      bun
      zoxide
      gh
      rustup
      uv
      ookla-speedtest
      mold
      sqlite
      containerd
      fastfetch
      openssl
      pkg-config
      direnv
      git-filter-repo
      go
      gtk4
      gtk3
      gtk2
      hyperfine
      jdk
      jq
      kmod
      lz4
      maven
      gradle
      musl
      oha
      protobuf
      qemu
      valgrind
      wl-clipboard
      hex
      nixfmt-rfc-style
      mpi
      mpi.dev
      age
      chezmoi
      nix-output-monitor
      nix-init
      trashy

      llvmPackages_20.clang-tools
      llvmPackages_20.clang-manpages
      llvmPackages_20.openmp
      llvmPackages_20.clangUseLLVM
      llvmPackages_20.bintools-unwrapped

      bear
      tokei
      eza
      bat
      ripgrep
      fd
      vulkan-tools
      libva-utils
      vdpauinfo
      mesa-demos
      vulkan-loader
      sd

      ffmpeg-full
      nixd
      docker
      turso-cli
      clinfo
      opencl-headers
      mesa
      libgcc
      volta
      python3Full
      pixi
    ]
    ++ [ (if config.nvidia.driver.enable then pkgs.btop-cuda else pkgs.btop) ];
}
