{ pkgs, config, ... }:

{
  environment.systemPackages =
    with pkgs;
    [
      neovim
      cachix
      file
      shellcheck
      gcc
      moor
      dust
      rm-improved
      wget
      gnumake
      ninja
      git
      delta
      unzip
      zsh
      stow
      curl
      cmake
      imagemagick
      gifsicle
      openssh
      openssl.out
      oh-my-posh
      fzf
      atuin
      pkgs.unstable.bun
      zoxide
      gh
      rustup
      pkgs.unstable.uv
      ookla-speedtest
      mold
      sqlite
      containerd
      fastfetch
      openssl
      pkg-config
      direnv
      git-filter-repo
      go
      gtk4
      gtk3
      gtk2
      hyperfine
      jdk
      jq
      kmod
      lz4
      maven
      gradle
      musl
      oha
      protobuf
      qemu
      lazygit
      valgrind
      wl-clipboard
      hex
      nixfmt-rfc-style
      age
      chezmoi
      nix-output-monitor
      nix-init
      trashy
      zip
      gdb
      nodejs

      llvmPackages_21.clang-tools
      llvmPackages_21.clang-manpages
      llvmPackages_21.openmp
      llvmPackages_21.clangUseLLVM
      llvmPackages_21.bintools

      bear
      tokei
      eza
      bat
      ripgrep
      fd
      vulkan-tools
      libva-utils
      vdpauinfo
      mesa-demos
      vulkan-loader
      sd
      p7zip-rar
      cabextract
      zenity
      shfmt

      ffmpeg-full
      nixd
      docker
      turso-cli
      clinfo
      opencl-headers
      mesa
      libgcc
      volta
      python3
      pixi
      rclone

      man-pages
      man-pages-posix
    ]
    ++ [ (if config.nvidia.driver.enable then pkgs.btop-cuda else pkgs.btop) ];
}
