condense_wildcard_suffixes  = true
edition                     = "2021"
format_code_in_doc_comments = true
format_strings              = true
group_imports               = "StdExternalCrate"
hex_literal_case            = "Upper"
imports_granularity         = "Crate"
overflow_delimited_expr     = true
reorder_impl_items          = true
unstable_features           = true
use_field_init_shorthand    = true
use_try_shorthand           = true
wrap_comments               = true
